[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NODE_OPTIONS = "--max-old-space-size=4096"

# 1. WWW auf Non-WWW
[[redirects]]
  from = "https://www.velwebsolutions.de/*"
  to = "https://velwebsolutions.de/:splat"
  status = 301
  force = true

# 2. API-Routing (Netlify Functions)
# WICHTIG: Wir leiten /api/* auf die server-function um.
# Das 'force = true' ist entscheidend, damit Netlify nicht statisch sucht.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true

# 3. Nuxt Render Redirect (FÃ¼r alle anderen Seiten)
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.google.com https://www.gstatic.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' data: https://fonts.gstatic.com; img-src 'self' data: https://images.unsplash.com https://plus.unsplash.com; connect-src 'self' https://api.emailjs.com https://www.google.com/recaptcha/;"